### ISSUE TITLE
does not find components in the vendor directory

### ISSUE THREAD

**Issue by TreyBastian** [RicardoRamirezR/blade-nav.nvim#15]
I'm noticing with filament specifically, I haven't tested this in any other way, that if I gf on `<x-filament-tables::columns.layout>` for example it can't find the file.

**Comment by RicardoRamirezR** [comment]
Yep @TreyBastian, never thought in that

**Comment by RicardoRamirezR** [comment]
@TreyBastian I guess it should open `resources/views/components/vendor/filament/columns/layout.blade.php`, did it not?

**Comment by TreyBastian** [comment]
so that file is `vendor/filament/tables/resources/views/components/columns/column.blade.php` 

not resources/views of the app

**Comment by TreyBastian** [comment]
my thoughts are without having made the changes myself is there just any reason to not do the search and file match in `./**/*` that way it'll pickup blade files no matter where they are located

```lua
M.get_blade_files = function()
  local handle = io.popen('find resources/views -type f -name "*.blade.php" | sort')
  local result = handle:read("*a")
  handle:close()

  local files = {}
  for file in result:gmatch("[^\r\n]+") do
    local view_name = file:match("resources/views/(.*)%.blade%.php$")
    if view_name then
      view_name = view_name:gsub("/", ".")
      table.insert(files, view_name)
    end
  end

  return files
end
```

**Comment by RicardoRamirezR** [comment]
@TreyBastian

The code you mentioned is form cmp or coq completion not for `gf`, I try to narrow the search for speed. 

But the first fix to be done is that `<x-foo::` does not get any result.

**Comment by RicardoRamirezR** [comment]
@TreyBastian 

> so that file is `vendor/filament/tables/resources/views/components/columns/column.blade.php`
> 
> not resources/views of the app

or `vendor/filament/tables/resources/views/components/columns/layout.blade.php` ?

**Comment by TreyBastian** [comment]
exactly I would just expect to be able to jump to any blade file within my project to be honest. If I'm using the component somewhere I'd hope to be able to see the implementation.

**Comment by RicardoRamirezR** [comment]
@TreyBastian an initial support has been added.

**Comment by TreyBastian** [comment]
great, just tried it out and it works.

I don't want to throw another spanner in the mix here, but Mary-ui doesn't though. It's not one I actively use but it's one I've looked at so I figured I'd see what the situation is since you added a specific case for filament. 

that one unfortunately doesn't use blade.php files it just uses .php files and inlines the php with HTML tags in the render method

an example path is `vendor/robsontenorio/Mary/src/View/Components/Alert.php` is the `<x-alert>` element

I'm not saying you should support it, I'm just bringing awareness to it. I don't really know the answer to how to support all these potential scenarios easily apart from maybe just searching for classes that implement component or import volt functions and indexing them

**Comment by RicardoRamirezR** [comment]
@TreyBastian,

> great, just tried it out and it works.

Great!
 
> I don't want to throw another spanner in the mix here, but Mary-ui doesn't though. It's not one I actively use but it's one I've looked at so I figured I'd see what the situation is since you added a specific case for filament.

The support added is for packages in general, an a touch for Filament.

> that one unfortunately doesn't use blade.php files it just uses .php files and inlines the php with HTML tags in the render method
> 
> an example path is `vendor/robsontenorio/Mary/src/View/Components/Alert.php` is the `<x-alert>` element
> 
> I'm not saying you should support it, I'm just bringing awareness to it. I don't really know the answer to how to support all these potential scenarios easily apart from maybe just searching for classes that implement component or import volt functions and indexing them

They are render Closures, since I don't use them I haven't thought about it.

Let me see

**Comment by TreyBastian** [comment]
Fantastic, yea that's not a request for me to support those, but just figured I'd help by bringing awareness to them. 

Thanks for that quick support for the filament though that really helps my workflow, I really appreciate it.

**Comment by RicardoRamirezR** [comment]
@TreyBastian, there is an Laravel Artisan command that needs to be in `app/Console/Command/BladeNav.php` in order to get the `gf` working on Mary and others actually.
