### ISSUE TITLE
Slow when navigating through livewire components

### ISSUE THREAD

**Issue by rizkyilhampra** [RicardoRamirezR/blade-nav.nvim#19]
Hi. I was using `v1.4` then recently updated your plugin to `v1.5.4` and I noticed there is slowness when navigating blade files or livewire components. It takes maybe 1-2 seconds to see the component I want to look for. I'm sorry I don't know how to debug to show you the exact time it takes.

Here is my neovim version i used 
```
NVIM v0.10.1
type: Release
2.1.1713484068
"nvim -V1 -v" for more info
```

I know the `gf` key will trigger some processes instead of only navigating through blade files or livewire components, so it's understandable for being slow. My workaround is, maybe make it configurable to set keymaps for different process?

Thanks

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra thanks for reporting. Give a look at v1.6.0 to see if happens there please

**Comment by rizkyilhampra** [comment]
Yes it still hapen in v1.6.1. Here is some information

checkhealth output
```
blade-nav: require("blade-nav.health").check()

Blade Nav health check started ~
- OK fd 10.1.0
- OK PHP 8.3.9 (cli) (built: Jul  2 2024 15:37:13) (NTS)
- WARNING Blade command components-aliases not found
  to install it run the Ex command BladeNavInstallArtisanCommand
- OK composer.json
- OK resources/views
- OK vendor/composer/autoload_psr4.php
- OK Git repository found
```

I do run `BladeNavInstallArtisanCommand` in a laravel project, but it give me error
```
BladeNavInstallArtisanCommand Error writing file: Could not open file: /home/aquila/Projects/test/app/Console/Commands/BladeNav.php
```

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra thanks for the input.

The error was because `app/Console/Command` directory does not exist, that's why after making the command with `artisan` it worked, it is fixed now.

After `BladeNavInstallArtisan` worked, did `gf` on `<x-` is still slow?

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra a new command `BladeElapsedTimes` was added in v.1.6.2, please run it an report the output back.

**Comment by rizkyilhampra** [comment]
@RicardoRamirezR  First, i want to tell you, i do reproduce in Breeze laravel starter kit project instead my own. i do `BladeNavInstallArtisanCommand`  but it give me error, even with tried run `php artisan make:command`. Here is the error i got.
```
BladeNavInstallArtisanCommand Error executing Lua callback: Vim:E739: Cannot create directory /app: permission denied
stack traceback:
	[C]: in function 'mkdir'
	...ocal/share/nvim/lazy/blade-nav.nvim/lua/blade-nav/gf.lua:570: in function <...ocal/share/nvim/lazy/blade-nav.nvim/lua/blade-nav/gf.lua:560>
```
Then, i rollback the plugin into v1.6.1 to make the `BladeNavInstallArtisanCommand` work, and finally run `BladeElapsedTimes`.

Here is the output
```
02:28:07 AM msg_show   BladeElapsedTimes Elapsed time: 0.0351 seconds on check_blade_command
02:28:09 AM msg_show   BladeElapsedTimes Elapsed time: 0.0465 seconds on get_components_aliases
02:28:09 AM msg_show   BladeElapsedTimes Elapsed time: 0.0048 seconds on get_blade_files
02:28:09 AM msg_show   BladeElapsedTimes Elapsed time: 0.0042 seconds on get_root_dir
02:28:10 AM msg_show   BladeElapsedTimes Elapsed time: 0.0089 seconds on get_route_names
   Info  02:28:11 AM notify.info Error parsing JSON output
02:28:11 AM msg_show   BladeElapsedTimes Elapsed time: 0.0150 seconds on get_routes
```

If you don't mind i'll put in here my 53 second video how do i reproduce.

https://github.com/user-attachments/assets/37838fd3-778d-4ae3-ade3-ce7b35a0c47d

If you see the video, at the 23 second I trigger the gf key, then it finishes at the 26 second.

**Comment by RicardoRamirezR** [comment]
Check the new pre-release and let me know. If not works I will comment a section to test on it, then we'll see

**Comment by rizkyilhampra** [comment]
@RicardoRamirezR it still happen

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra trey v1.6.4 please

**Comment by rizkyilhampra** [comment]
Yes it worksss now, thanks @RicardoRamirezR

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra great to know, I've comment an implementation, I'll dig further to provide full solution

**Comment by RicardoRamirezR** [comment]
Can you use main branch please and see if it works. Trying to find the culprit

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra can you use main branch please and see if it works. Trying to find the culprit

**Comment by rizkyilhampra** [comment]
yes it still work

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra, try main again please., it will fails. Then edit the `app/Console/Command/BladeNav.php` the in the handle before line 28 add a `return echo json_encode([]);` then test again please

**Comment by rizkyilhampra** [comment]
> @rizkyilhampra can you use main branch please and see if it works. I'm trying to find the culprit

It's not work, my bad if you had see my reply before.

**Comment by RicardoRamirezR** [comment]
No problem

**Comment by RicardoRamirezR** [comment]
Let's try again

**Comment by rizkyilhampra** [comment]
> @rizkyilhampra, try main again please., it will fails. Then edit the `app/Console/Command/BladeNav.php` the in the handle before line 29 add a `return echo json_encode([]);` then test again please

i see the decrement, but it's still not fast like i was in v1.4. I'm still ok with this

**Comment by RicardoRamirezR** [comment]
Let's try again

**Comment by rizkyilhampra** [comment]
same i just see the decrement

**Comment by RicardoRamirezR** [comment]
Can you run `php artisan --format=json` to see if it is the culprit

**Comment by rizkyilhampra** [comment]
Is too much. You still want to see all the output?

![image](https://github.com/user-attachments/assets/49e5dc13-d11e-49a5-b95f-6fbe81906318)

**Comment by RicardoRamirezR** [comment]
Nop, it ok

**Comment by RicardoRamirezR** [comment]
Please check again fro main branch

**Comment by rizkyilhampra** [comment]
it workss

**Comment by rizkyilhampra** [comment]
I'm not sure, i think you got typo in here
https://github.com/RicardoRamirezR/blade-nav.nvim/blob/fabdfc9a9db7aa66eb0fe8adf36b9740a53e578b/lua/blade-nav/utils.lua#L379

**Comment by RicardoRamirezR** [comment]
Yep, thank you. I've made the correction. Please try again to check it is working

**Comment by RicardoRamirezR** [comment]
@rizkyilhampra the updated release v1.6.5 has the final fix.

**Comment by rizkyilhampra** [comment]
@RicardoRamirezR Ya it works now. Thanks
