### ISSUE TITLE
Does not account for `index` files

### ISSUE THREAD

**Issue by calebdw** [RicardoRamirezR/blade-nav.nvim#2]
Hello!

Awesome plugin!!

I just wanted to let you know that this does not open [anonymous-index-components](https://laravel.com/docs/10.x/blade#anonymous-index-components):

for example, I have the following file:
```
views/components/form/index.blade.php
```

Clicking `gf` on the `<x-form ...>` tag prompts me to create the file instead of opening the `index` file.

Thanks!

**Comment by RicardoRamirezR** [comment]
Thanks @calebdw 

I can't reproduce the issue.

In my case, the <x-form.input /> did not exist, so I created it anonymously, then used gf and it worked. 😏

![form-index](https://github.com/RicardoRamirezR/blade-nav.nvim/assets/6526545/858b294d-b7e2-4efe-9b48-e5559ae38423)

**Comment by RicardoRamirezR** [comment]
@calebdw please position the cursor in any place of form.input and then `gf`

**Comment by calebdw** [comment]
I have this code:

```blade
                <x-form>
                    <div>foo</div>
                </x-form>
```

And the associated blade for the `x-form` is located at `resources/views/components/form/index.blade.php`.


Placing my cursor on `x-form` causes the prompt to be shown:

![image](https://github.com/RicardoRamirezR/blade-nav.nvim/assets/4176520/8cfd2746-f8c1-4aa6-9816-7971c61bbe34)

**Comment by RicardoRamirezR** [comment]
Ohh there are two issues:

1. incorrectly parsing the name as `form>`
2. the index.blade.php of form, I was not aware of this

**Comment by RicardoRamirezR** [comment]
@calebdw done!

**Comment by calebdw** [comment]
That was fast!

**Comment by RicardoRamirezR** [comment]
@calebdw 

> I have this code:
> 
> ```
>                 <x-form>
>                     <div>foo</div>
>                 </x-form>
> ```
> 

If the anonymous-index-components does not exist, should there be an option to create it?

**Comment by calebdw** [comment]
I suppose that could be on the list of recommendations,  you might have to create the directory though
