### ISSUE TITLE
`gf` mapping breaks navigating to file under cursor

### ISSUE THREAD

**Issue by calebdw** [RicardoRamirezR/blade-nav.nvim#21]
Hello!

Pressing `gf` to navigate to the file under my cursor no longer works, and I noticed this remaps it. I'm fine with that in blade files because there's not really file paths in blade, but I can't have it replace that functionality globally.

Thanks!

**Comment by RicardoRamirezR** [comment]
Hi @calebdw, 

In a `composer.json`:
```json
"autoload-dev": {
    "files": [
        "tests/utilities/functions.php"
    ],
    "psr-4": {
        "Tests\\": "tests/"
    }
},
```

I do `gf` over the functions.php the file is opened, then open  any blade file, then back to `composer.json` then `gf` again and still works.

I have `gf` mapped to `:edit <cfile>`, btw

Can you give an example to reproduce it, please

**Comment by RicardoRamirezR** [comment]
I made it less intrusive, but still should work in blade and pho files. Let me know.

**Comment by calebdw** [comment]
I think that worked, thangs!

**Comment by calebdw** [comment]
Completed in https://github.com/RicardoRamirezR/blade-nav.nvim/commit/56c1538a093688a5a24ade3c1bcf7b0e3a15eee9
