### ISSUE TITLE
E447: Can't find file "x-component.name" in path with customs locations

### ISSUE THREAD

**Issue by gmnz** [RicardoRamirezR/blade-nav.nvim#24]
Hi,

So basically the problem is described in the tittle. gf doesn't work for me at all, always gives me the error mentioned above. Any ideas why this could be? The views are in these dirs:

resources/views/{common  components  errors  staremesto  vendor}

Is there any way I can help the plugin find them?

**Comment by RicardoRamirezR** [comment]
Hi @gmnz, the locations are Laravel one's `app/View/Components` and `resources/views/components` as  [Laravel docs](https://laravel.com/docs/11.x/blade#components) states

**Comment by gmnz** [comment]
OK, so if my Laravel app is using components stored inside resources/views/other_than_components_dir, then there's no way to make "gf" work for these components? It works only for components stored in resources/views/components and its subdirs?

**Comment by RicardoRamirezR** [comment]
Since I’m not aware how Laravel can handle your components in non standard location, nor have any case on my own, yes the standard ones locations. PR are welcome

**Comment by gmnz** [comment]
I searched through the project's code and consulted it with my colleague and the method to make Laravel work with custom view paths that's used in this case is this one:

https://stackoverflow.com/questions/27458439/how-to-set-view-file-path-in-laravel -> accepted answer -> Method 3

Any hints where to start if I wanted to add support for this? If it's not too complicated I may try.

**Comment by RicardoRamirezR** [comment]
How are you setting the view file path?

**Comment by gmnz** [comment]
I'm not really sure what you're asking for. Is this it?

        View::addLocation(resource_path('views/common'));

It's used inside app/Http/Controllers/Controller.php -> __construct

**Comment by RicardoRamirezR** [comment]
Yes, I'll take a look at it

**Comment by datsudo** [comment]
This also happens to me. I have the components placed in `resources/views/components` but still doesn't work.

But here's the catch: the `gf` works when the component that I want to navigate is the first one that I open before the file that uses it:


https://github.com/user-attachments/assets/5f00d7bd-5691-4037-892e-bcecbcf6cbff

**Comment by RicardoRamirezR** [comment]
Hi @datsudo, thank for sharing. Is not the same issue, @gmnz has a custom view location

**Comment by tylerdak** [comment]
Just here to say I would love to see support added for jumping to associated blade files in custom view directories if possible (i.e. ./views instead of ./resources/views). However, the standard paths seem to be hardcoded into much of the codebase, so that might be a big undertaking.

**Comment by RicardoRamirezR** [comment]
@gmnz and @tylerdak, the way I'll go is to make a Artisan command to obtain the view paths and use them instead of the hardcoded's one via config flag.

As soon as a free time window appears will work on it.

**Comment by RicardoRamirezR** [comment]
I like the second, the first one is to global in my opinion, not all project has the same.

The second one but using defaults on `exrc` sound better to me. if `exrc` is on, Neovim will pick it automatically, you can have other options there also.

**Comment by tylerdak** [comment]
Ah okay, yeah didn't realize `exrc` had other benefits. Fairly new to nvim and haven't seen it before. Sounds good!

**Comment by RicardoRamirezR** [comment]
@tylerdak, @gmnz take a look at `main`, you can use any `exrc` file supported since neovim will read it automatically. i.e. `.nvim.lua`

```lua
vim.g.blade_nav = {
  laravel_componets = {
    "resources/views/common",
  }
}
```

And let me know

**Comment by tylerdak** [comment]
That works for me!

For anyone else, if you haven't used `exrc` before, it needs to be enabled somewhere in your nvim config:
`vim.o.exrc = true`

**Comment by RicardoRamirezR** [comment]
Lets wait one week to see if there is any issue, and then I'll make a release

**Comment by gmnz** [comment]
Hi, sorry I didn't respond before, couldn't find time for this. So I tested the plugin again like this (using LazyVim):

```lua
vim.o.exrc = true
vim.g.blade_nav = {
  laravel_components = {
    "resources/views/common",
    "resources/views/errors",
    "resources/views/staremesto",
    "resources/views/vendor",
  },
}

return {
  "ricardoramirezr/blade-nav.nvim",
  dependencies = { -- totally optional
    "hrsh7th/nvim-cmp", -- if using nvim-cmp
    -- { "ms-jpq/coq_nvim", branch = "coq" }, -- if using coq
  },
  ft = { "blade", "php" }, -- optional, improves startup time
  opts = {
    close_tag_on_complete = true, -- default: true
  },
}
```

and I'm trying to jump from this file:

resources/views/staremesto/advertisement/detail.blade.php

to this file:

resources/views/common/components/document-viewer/index.blade.php

but when using gf on the file's tag:

        <x-document-viewer.index columns="4" :publishing-files="$values"></x-document-viewer.index>

instead of going to the file it offers me to create the file:

![image](https://github.com/user-attachments/assets/424a64e0-bcd9-4b9d-a9c8-88be406df3e1)

Seems like it can nearly figure out the right path but it misses the "components" subdir.

In other cases I still get the error I mentioned in the title of this issue.

**Comment by tylerdak** [comment]
Give it the components folder, not the parent folder 

e.g. "resources/views/common/components"

**Comment by gmnz** [comment]
@tylerdak But there are also blade files outside the components dirs in the sibling dirs... Guess I'll have to dynamically scan through all the dirs when the editor is starting and then use the resulting list in laravel_components = {}
