### ISSUE TITLE
Support for COQ

### ISSUE THREAD

**Issue by Mte90** [RicardoRamirezR/blade-nav.nvim#8]
I don't use nvim-cmp but https://github.com/ms-jpq/coq_nvim maybe this plugin can add the support for that

in case for inspiration I did a custom source for wordpress hooks for the same plugin https://github.com/Mte90/coq_wordpress

**Comment by RicardoRamirezR** [comment]
Hi @Mte90, I will take look at it.

The other repo won't receive any updates (lali-components)

**Comment by Mte90** [comment]
Ok sorry for the duplicate but the readme wasn't clear.

**Comment by RicardoRamirezR** [comment]
No problem, I'll add it to the readme

**Comment by RicardoRamirezR** [comment]
@Mte90 did it for PHP files, view, View::make and Route::view. For blade files PR are welcome.

Be aware of  `coq_settings.match.max_results`

**Comment by Mte90** [comment]
Cool!
You forgot to mention in in the readme :-)

I will do a PR to coq to add in their documentation

**Comment by RicardoRamirezR** [comment]
@Mte90 thank you for the mention.

BTW, I've added coq for blade files also
