### ISSUE TITLE
cmp does not give referenece for view

### ISSUE THREAD

**Issue by RayGuo-ergou** [RicardoRamirezR/blade-nav.nvim#9]
Hi first of all thanks for this plugin!! I have been finding this kind of plugin for a while. What you did is super useful.

Just want to report a bug related to the cmp reference: https://github.com/RicardoRamirezR/blade-nav.nvim/blob/main/lua/blade-nav/cmp_php.lua#L54

this does not seem right to me as the character followed by `view` should be `(`, so at the moment I have to enter a alphabet follow by `view` to get the list.

![image](https://github.com/RicardoRamirezR/blade-nav.nvim/assets/33137074/404314c3-880e-4753-baab-7045be3f775e)
![image](https://github.com/RicardoRamirezR/blade-nav.nvim/assets/33137074/95636f23-2774-4dd1-9a94-32759a1ceac6)

I am willing to make a PR for this but probably not today.

**Comment by RayGuo-ergou** [comment]
or is this intentional? like for performance reason

**Comment by RicardoRamirezR** [comment]
@RayGuo-ergou  glad you liked

the idea was to write view followed by the view name, that way is working for you?

**Comment by RayGuo-ergou** [comment]
Maybe just me but I feel to type `view('` then wait for auto completion is more intuitive.

**Comment by RicardoRamirezR** [comment]
@RayGuo-ergou now you can use it with `view('`

**Comment by RayGuo-ergou** [comment]
Thanks!
